version: "3"

networks:
  monitoring:

services:
  grafana:
    image: grafana/grafana:8.0.3
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - ./grafana/var/lib/grafana:/var/lib/grafana
    user: "1000"
    environment:
      - GF_METRICS_ENABLED=true
      - GF_METRICS_DISABLE_TOTAL_STATS=false

  prometheus:
    image: prom/prometheus:v2.28.0
    ports:
      - 9090:9090
    networks:
      - monitoring
    volumes:
      - ./prometheus/etc/prometheus:/etc/prometheus
      - ./prometheus/prometheus:/prometheus
    user: "1000"

