scrape_configs:
  - job_name: 'grafana'
    scrape_interval: 15s
    scrape_timeout: 5s
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
